src/Entity/Comment.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\CommentRepository")
 */
class Comment
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    // add your own fields
    
    /**
     *@ORM\Column(type="string",length=45)
     */
    private $comment;
    /**
     *@ORM\Column(type="datetime")
     */
    private $create_date;
    
    /**
     * @ORM\ManyToOne(targetEntity= "App\Entity\User",inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $user;
    function getUser_id(){
        return $this->user;
    }
    function setUser(User $user){
        $this->user=$user;
    }
    
    /**
     * @ORM\ManyToOne(targetEntity= "App\Entity\Post",inversedBy="comments")
     * @ORM\JoinColumn(nullable=false)
     */
    private $post;
    function getPost_id(){
        return $this->post;
    }
    function setPost(Post $post){
        $this->post=$post;
    }

   
    function getComment() {
        return $this->comment;
    }

    function getCreate_date() {
        return $this->create_date;
    }


    function setComment($comment) {
        $this->comment = $comment;
    }

    function setCreate_date($create_date) {
        $this->create_date = $create_date;
    }

    function getId() {
        return $this->id;
    }


    
}

src/Entity/Post.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;

/**
 * @ORM\Entity(repositoryClass="App\Repository\PostRepository")
 */
class Post
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    // add your own fields
    
    /**
     *@ORM\Column(type="string",length=45)
     */
    private $title;
    /**
     *@ORM\Column(type="text")
     */
    private $content;
    /**
     *@ORM\Column(type="datetime")
     */
    private $create_date;   
    
    
    /**
    * @ORM\ManyToOne(targetEntity="App\Entity\User",inversedBy="posts")
    * @ORM\JoinColumn(nullable=true)
    */
    private $user;
    public function getUser_id(){
    return $this->user;
    }
    function setUser($user) {
        $this->user = $user;
    }

    /**
     * Many Posts have Many Tags.
     * @ORM\ManyToMany(targetEntity="Tag", inversedBy="posts", cascade={"persist"})
     * @ORM\JoinTable(name="post_tags")
     */
    private $tags;


    /**
     *@ORM\OneToMany(targetEntity= "App\Entity\Comment",mappedBy="post")
     */
    private $comments;
    public function getComments(){
        return $this->comments;
    }
    
    
    function getTitle() {
        return $this->title;
    }

    function getContent() {
        return $this->content;
    }

    function getCreate_date() {
        return $this->create_date;
    }
    function getCreatedate() {
        return $this->create_date;
    }


    function getTags() {
        return $this->tags;
    }

    function setTitle($title) {
        $this->title = $title;
    }

    function setContent($content) {
        $this->content = $content;
    }

    function setCreatedate($create_date) {
        $this->create_date = $create_date;
    }


    function setTags($tags) {
        $this->tags = $tags;
    }
    public function __construct(){
    $this->user=new ArrayCollection();
    $this->tags = new ArrayCollection();
    $this->comments=new ArrayCollection();
    }
    function getId() {
        return $this->id;
    }



}

src/Form/PostType.php
<?php

    namespace App\Form;

    use Symfony\Component\Form\AbstractType;
    use Symfony\Component\Form\FormBuilderInterface;
    use Symfony\Component\OptionsResolver\OptionsResolver;
    use Symfony\Component\Form\Extension\Core\Type\DateTimeType;
    use App\Form\Type\TagsInputType;
    use Symfony\Component\Form\Extension\Core\Type\SubmitType;
    use App\Entity\Post;
    
    /**
 * Description of PostType
 *
 * @author linux
 */
class PostType extends AbstractType
{
    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        // For the full reference of options defined by each form field type
        // see https://symfony.com/doc/current/reference/forms/types.html

        // By default, form fields include the 'required' attribute, which enables
        // the client-side form validation. This means that you can't test the
        // server-side validation errors from the browser. To temporarily disable
        // this validation, set the 'required' attribute to 'false':
        // $builder->add('title', null, ['required' => false, ...]);

        $builder
            ->add('title', null, [
                'attr' => ['autofocus' => true],
                'label' => 'Title',
                'attr'=>[ 
                                'class'=>'form-control'
                        ]
            ])
            ->add('content', null, [
                'label' => 'Content',
                'required' => false,
                'attr'=>[ 
                                'class'=>'form-control'
                        ]
            ])
            ->add('create_date', DateTimeType::class, [
                'label' => 'Published at',
                'widget'=>'single_text',
                'attr'=>[ 
                                'class'=>'form-control js-datepicker'
                        ]
            ])
            ->add('tags', TagsInputType::class, [
                'label' => 'Tags',
                
                'required' => false,
                'attr'=>[ 
                                'data-role'=>'tagsinput',
                                'class'=>'form-control'
                        ]
            ])
                ->add('Signup', SubmitType::class,
                            ['label'=>'Save',
                                'attr'=>[ 
                                'class'=>'form-submit btn btn-success'
                        ]]);
    }

    /**
     * {@inheritdoc}
     */
    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Post::class,
        ]);
    }
}

src/Controller/PostController.php
<?php

namespace App\Controller;

use Symfony\Component\Routing\Annotation\Route;
use Symfony\Bundle\FrameworkBundle\Controller\Controller;
use Symfony\Component\HttpFoundation\Request;
use App\Entity\Post;
use App\Form\PostType;

class PostController extends Controller
{
    /**
     * @Route("/post", name="post")
     */
    public function index()
    {
        return $this->render('post/index.html.twig', [
            'controller_name' => 'PostController',
        ]);
    }
    
    /**
     * @Route("/newpost", name="newpost")
     */
    public function newPost(Request $request){
        
       $post=new Post();
       $user=$this->getUser();
       $post->setUser($user);
       $form = $this->createForm(PostType::class, $post); 
       
        //formulario
       $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {
           $post=$form->getData();
           $em = $this->getDoctrine()->getManager();
           $em->persist($post);
           $em->flush();
           return $this->redirectToRoute('homeaction');
       }
           return $this->render('post/createpost.html.twig', array(
            'user'=>$user,   
            'form' => $form->createView()            
        ));
    }
    /**
     * @Route("/post/{thispost}",name="post")
     */
    public function thisPost($thispost){
        $posts = $this->getDoctrine()->getRepository('App:Post')->findAll();
        $users = $this->getDoctrine()->getRepository('App:User')->findAll();
        $comments = $this->getDoctrine()->getRepository('App:Comment')->findAll();
        
        return $this->render('post/thispost.html.twig',[
            'thispost'=> $thispost,
            'posts' => $posts,
            'comments' => $comments,
            'users' => $users]);
    }
    /**
     * @Route("/post/{thispost}/editpost", name="editpost")
     */
    public function editPosts(Request $request){
        
       //this post
       $stringid = $request->attributes->get('thispost');
       $postid = (int)$stringid;
       $repository = $this->getDoctrine()->getRepository(Post::class);
       $post = $repository->find($postid);
       $user = $this->getUser();
       $form = $this->createForm(PostType::class, $post); 
       
        //formulario
       $form->handleRequest($request);
       if ($form->isSubmitted() && $form->isValid()) {
           $post=$form->getData();
           $em = $this->getDoctrine()->getManager();
           $em->persist($post);
           $em->flush();
           return $this->redirectToRoute('homeaction');
       }
           return $this->render('post/editpost.html.twig', array(
            'user'=>$user,
            'post'=>$post,
            'form' => $form->createView()            
        ));
    }

}

templates/post/createpost.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/estilo.css') }}"/>
    <link rel="stylesheet" href="{{ asset('assets/css/jquery-te-1.4.0.css') }}"/>
{% endblock %}

{% block body %}    
    <div class="col-lg-6 box-form">
    <h1>New post</h1>
            {{form_start(form)}}
                {{ form_row(form.title) }}
                {{ form_row(form.content) }}
                {{ form_row(form.create_date) }}
                {{ form_row(form.tags) }}
            {{ form_end(form) }}
    </div>
{% endblock %}
{% block javascripts %}
    {{parent()}}
    <script src="{{asset("assets/js/bootstrap-tagsinput.min.js")}}"></script>
    <script src="{{asset("assets/js/jquery-te-1.4.0.min.js")}}"></script>
    <script>
        $("textarea").jqte();
    </script>
    {%endblock%}

templates/post/editpost.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/estilo.css') }}"/>
    <link rel="stylesheet" href="{{ asset('assets/css/jquery-te-1.4.0.css') }}"/>
{% endblock %}

{% block body %}
    {% if app.user %}
            {% if post.user_id == app.user %}    
    <div class="col-lg-6 box-form">
    <h1>Edit post</h1>
            {{form_start(form)}}
                {{ form_row(form.title) }}
                {{ form_row(form.content) }}
                {{ form_row(form.create_date) }}
                {{ form_row(form.tags) }}
            {{ form_end(form) }}
    </div>
            {% endif %}
        {% endif %}
{% endblock %}
{% block javascripts %}
    {{parent()}}
    <script src="{{asset("assets/js/bootstrap-tagsinput.min.js")}}"></script>
    <script src="{{asset("assets/js/jquery-te-1.4.0.min.js")}}"></script>
    <script>
        $("textarea").jqte();
    </script>
    {%endblock%}

templates/post/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello {{ controller_name }}!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>src/Controller/PostController.php</code></li>
        <li>Your template at <code>templates/post/index.html.twig</code></li>
    </ul>
</div>
{% endblock %}

templates/post/thispost.html.twig
{% extends 'base.html.twig' %}

{% block stylesheets %}
    {{ parent() }}
    <link rel="stylesheet" href="{{ asset('assets/css/estilo.css') }}"/>
{% endblock %}

{% block body %}
    <!-- check is a flag variable, if locates the post, will print it -->
    {% set check = 0 %}
    <div class="container">
        <div class="jumbotron">
    {% for post in posts %}
        {% if post.id == thispost %}
                {% set check = 1 %}
        {% endif %}
    {% endfor %}
    {% if check == 1 %}
        {% for post in posts %}
            {% if post.id == thispost %}
                <h1>{{post.title}}</h1>
                <h3>Date: <i>{{ post.create_date|date('d-m-Y') }}</i></h3>
                <h3>User: <i>{% for user in users %}
                                {% if post.user_id == user %}
                                    {{ user.username }}
                                {% endif %}
                                {% endfor %}</i></h3>
                <hr>
                <p>{{post.content | raw }}</p>
            <!-- comment section -->
            <hr>
            <h3><i>Comments</i></h3>
            {% for comment in comments %}
                {% if comment.post_id == post %}
                    <hr>
                    <p>                    
                    {% for user in users %}
                        {% if comment.user_id == user %}
                            {{ user.username }}
                        {% endif %}
                    {% endfor %}
                    - {{ comment.create_date|date('d-m-Y H:m') }}<br>
                    {{comment.comment | raw }}
                    </p>
                {% endif %}
            {% endfor %}
            {% if app.user %}
                <p><a href="/post/{{ post.id }}/addcomment">Add comment</a></p>
            {% endif %}
            {% endif %}
        {% endfor %}
    {% else %}
        <h1>Post not located in archive.</h1>
    {% endif %}
        </div>
    </div>
{% endblock %}